apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
  ports: 
  - targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}      